#!/usr/bin/env python

import BaseHTTPServer
import urllib2
import re

base_url = r"http://0.0.0.0:8000/"


def rewrite_link(link):
    pass

class TunnelHandler(BaseHTTPServer.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path[0] == '/':
            self.path = self.path[1:]

        try:
            fd = urllib2.urlopen(self.path)
        except urllib2.URLError:
            self.wfile.write("400 : The URL " + self.path + " isn't reachable")
            return

        if fd.info().type == "text/html":
            content = fd.read()
            def reg_repl(m):
                return base_url + "\0"

            # A replacement function for a relative path (like /~karim)
            def relative_repl(m):
                if m.group(1).find('http') != -1:
                    print "guh"
                    print "rewritten to : " + base_url + m.group(1)
                    return base_url + m.group(1)

                print "rewritten to : " "http://" + self.path + "/" +  m.group(1)
                return base_url + self.path + "/" + m.group(1)

            # Relative urls
            re.sub("href=\"([a-zA-Z0-9\/\\\:\?\%\.\&\;=#\-\_\!\+\~]*)\"", relative_repl, content)

            # Regular urls
            # re.sub("href=\"http:\/\/([a-zA-Z0-9\/\\\:\?\%\.\&\;=#\-\_\!\+\~]*)\"", reg_repl, content)

            self.wfile.write(content)
        else:
            self.wfile.write(fd.read())

if __name__ == "__main__":
    server_address = ('', 8000)
    httpd = BaseHTTPServer.HTTPServer(server_address, TunnelHandler)
    httpd.serve_forever()

